version: "3"
services:
  backend:
    build:
      context: ./backend/
    depends_on:
      - postgres
    ports:
      - "3001:3001"
      - "9229:9229"
    volumes:
      - "${PWD}/backend:/usr/src/app"
    environment:
      DATABASE_URL: "postgresql://username:password@postgres:5432/mixbook_db?schema=public&connect_timeout=300"

  # frontend:
  #   build:
  #     context: ./frontend/
  #   volumes:
  #     - ./frontend/:/usr/src/app
  #   ports:
  #     - "3000:3000"

  postgres:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mixbook_db
    ports:
      - "54320:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
