version: "3"
services:
  backend:
    build:
      context: ./backend/
    depends_on:
      - postgres
    ports:
      - "3001:3001"
      - "9229:9229"
    volumes:
      - "${PWD}/backend:/usr/src/app"

  frontend:
    build:
      context: ./frontend/
    volumes:
      - ./frontend/:/usr/src/app
    ports:
      - "3000:3000"

  postgres:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: