version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "3001:3001"
      - "9229:9229"
    volumes:
      - "${PWD}/backend:/usr/src/app"

  postgres:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: