name: "build app"
on: workflow_dispatch

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: "repo checkout"
        uses: actions/checkout@v3
      - name: "setup node"
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: "run fe build"
        run: |
          chmod +x ./fe-build-prod.sh
          ./fe-build-prod.sh
